### ISSUE TITLE
new mongo fails

### ISSUE THREAD

**Issue by interfaith** [CollectionFS/Meteor-CollectionFS#616]
Error: Error storing uploaded file to TempStore: driver is incompatible with this server version

mongo 2.6.8 works , the new mongo 3 fails ?

**Comment by interfaith** [comment]
SA GridFS - ERROR! { [MongoError: driver is incompatible with this server version] name: 'MongoError' }

**Comment by interfaith** [comment]
over writing the 3.x binaries with 2.6.8 binaries works

**Comment by aldeed** [comment]
@interfaith I just updated to the latest mongodb node pkg and republished. `meteor update cfs:gridfs` and see if that fixes it.

**Comment by interfaith** [comment]
no luck..
SA GridFS - ERROR! { [MongoError: driver is incompatible with this server
version] name: 'MongoError' }

/home/ubuntu/0321/bundle/programs/server/npm/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/base.js:242
        throw message;
              ^
Error: Error storing uploaded file to TempStore: driver is incompatible
with this server version
    at EventEmitter.<anonymous> (packages/cfs:collection/common.js:153:1)
    at EventEmitter.emit (events.js:117:20)
    at Stream.<anonymous> (packages/cfs:tempstore/tempStore.js:335:1)
    at Stream.emit (events.js:117:20)
    at Stream._error
(/home/ubuntu/0321/bundle/programs/server/npm/cfs_gridfs/node_modules/gridfs-stream/lib/writestream.js:190:8)
    at
/home/ubuntu/0321/bundle/programs/server/npm/cfs_gridfs/node_modules/gridfs-stream/lib/writestream.js:128:28
    at
/home/ubuntu/0321/bundle/programs/server/npm/cfs_gridfs/node_modules/mongodb/lib/mongodb/gridfs/gridstore.js:497:57
    at
/home/ubuntu/0321/bundle/programs/server/npm/cfs_gridfs/node_modules/mongodb/lib/mongodb/gridfs/chunk.js:156:13
    at
/home/ubuntu/0321/bundle/programs/server/npm/cfs_gridfs/node_modules/mongodb/lib/mongodb/collection/core.js:210:9
    at __executeInsertCommand
(/home/ubuntu/0321/bundle/programs/server/npm/cfs_gridfs/node_modules/mongodb/lib/mongodb/db.js:1829:12)


On Sat, Mar 21, 2015 at 2:57 PM, Eric Dobbertin <notifications@github.com>
wrote:

> @interfaith <https://github.com/interfaith> I just updated to the latest
> mongodb node pkg and republished. meteor update cfs:gridfs and see if
> that fixes it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CollectionFS/Meteor-CollectionFS/issues/616#issuecomment-84459061>
> .
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D

**Comment by interfaith** [comment]
fixed ! the update worked

On Sat, Mar 21, 2015 at 4:46 PM, Mark Spowage <spowage@gmail.com> wrote:

> no luck..
> SA GridFS - ERROR! { [MongoError: driver is incompatible with this server
> version] name: 'MongoError' }
>
>
> /home/ubuntu/0321/bundle/programs/server/npm/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/base.js:242
>         throw message;
>               ^
> Error: Error storing uploaded file to TempStore: driver is incompatible
> with this server version
>     at EventEmitter.<anonymous> (packages/cfs:collection/common.js:153:1)
>     at EventEmitter.emit (events.js:117:20)
>     at Stream.<anonymous> (packages/cfs:tempstore/tempStore.js:335:1)
>     at Stream.emit (events.js:117:20)
>     at Stream._error
> (/home/ubuntu/0321/bundle/programs/server/npm/cfs_gridfs/node_modules/gridfs-stream/lib/writestream.js:190:8)
>     at
> /home/ubuntu/0321/bundle/programs/server/npm/cfs_gridfs/node_modules/gridfs-stream/lib/writestream.js:128:28
>     at
> /home/ubuntu/0321/bundle/programs/server/npm/cfs_gridfs/node_modules/mongodb/lib/mongodb/gridfs/gridstore.js:497:57
>     at
> /home/ubuntu/0321/bundle/programs/server/npm/cfs_gridfs/node_modules/mongodb/lib/mongodb/gridfs/chunk.js:156:13
>     at
> /home/ubuntu/0321/bundle/programs/server/npm/cfs_gridfs/node_modules/mongodb/lib/mongodb/collection/core.js:210:9
>     at __executeInsertCommand
> (/home/ubuntu/0321/bundle/programs/server/npm/cfs_gridfs/node_modules/mongodb/lib/mongodb/db.js:1829:12)
>
>
> On Sat, Mar 21, 2015 at 2:57 PM, Eric Dobbertin <notifications@github.com>
> wrote:
>
>> @interfaith <https://github.com/interfaith> I just updated to the latest
>> mongodb node pkg and republished. meteor update cfs:gridfs and see if
>> that fixes it.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/CollectionFS/Meteor-CollectionFS/issues/616#issuecomment-84459061>
>> .
>>
>
>
>
> --
> -----
> Fight back spam! Download the Blue Frog.
> http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D

**Comment by victorbstan** [comment]
Hmm, which version of cfs:gridfs fixes this? I have:

`cfs:gridfs  upgraded from 0.0.31 to 0.0.32`

I am deploying to Ubuntu 14 and deployment and uploading seems to work but I still get this same error.

```
SA GridFS - ERROR! { [MongoError: driver is incompatible with this server version] name: 'MongoError' }[dayplan.me]
[dayplan.me]
/opt/qs/app/programs/server/npm/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/base.js:242[dayplan.me]
[dayplan.me]         throw message;
[dayplan.me]               ^[dayplan.me]
[dayplan.me] Error: Error storing uploaded file to TempStore: driver is incompatible with this server version
    at EventEmitter.<anonymous> (packages/cfs:collection/common.js:153:1)
    at EventEmitter.emit (events.js:98:17)
    at Stream.<anonymous> (packages/cfs:tempstore/tempStore.js:335:1)
    at Stream.emit (events.js:117:20)
    at Stream._error (/opt/qs/app/programs/server/npm/cfs_gridfs/node_modules/gridfs-stream/lib/writestream.js:190:8)
    at /opt/qs/app/programs/server/npm/cfs_gridfs/node_modules/gridfs-stream/lib/writestream.js:175:26
    at /opt/qs/app/programs/server/npm/cfs_gridfs/node_modules/mongodb/lib/mongodb/gridfs/gridstore.js:152:24
    at /opt/qs/app/programs/server/npm/cfs_gridfs/node_modules/mongodb/lib/mongodb/db.js:1430:36
    at __executeInsertCommand (/opt/qs/app/programs/server/npm/cfs_gridfs/node_modules/mongodb/lib/mongodb/db.js:1829:12)
    at Db._executeInsertCommand (/opt/qs/app/programs/server/npm/cfs_gridfs/node_modules/mongodb/lib/mongodb/db.js:1930:5)
```

**Comment by aldeed** [comment]
`0.0.32` has the latest npm pkg.
